resource "azurerm_postgresql_server" "example" {
  name                = "example-postgres"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku_name            = "B_Gen5_1"
  storage_mb          = 5120
  version             = "11"
}
