version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - marketplace-network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name
    networks:
      - marketplace-network

  azure-blob-emulator:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azure-blob-emulator
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    environment:
      - AZURITE_ACCOUNT=myaccount
      - AZURITE_ACCOUNT_KEY=myaccountkey
      - AZURITE_BLOB_PORT=10000
      - AZURITE_QUEUE_PORT=10001
      - AZURITE_TABLE_PORT=10002
    networks:
      - marketplace-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - marketplace-network

networks:
  marketplace-network:
    driver: bridge

volumes:
  elasticsearch_data:
