resource "azurerm_servicebus_namespace" "example" {
  name                = "example-servicebus"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku                 = "Standard"
}
