variable "resource_group_name" {
  description = "Name of the resource group"
}

variable "location" {
  description = "Azure region"
}

variable "cluster_name" {
  description = "Name of the AKS cluster"
}

variable "kubernetes_version" {
  description = "Kubernetes version"
}

variable "node_count" {
  description = "Number of nodes in the AKS cluster"
}

variable "vm_size" {
  description = "VM size for AKS nodes"
}

variable "key_vault_object_id" {
  description = "Object ID of the managed identity for Key Vault access"
}

resource "azurerm_kubernetes_cluster" "aks" {
  name                = var.cluster_name
  location            = var.location
  resource_group_name = var.resource_group_name
  dns_prefix          = "${var.cluster_name}-dns"
  kubernetes_version = var.kubernetes_version

  default_node_pool {
    name       = "default"
    node_count = var.node_count
    vm_size    = var.vm_size
  }

  network_profile {
    network_plugin = "azure"
    load_balancer_sku = "Standard"
  }

  identity {
    type = "UserAssigned"
    user_assigned_identity_id = var.key_vault_object_id
  }

  tags = {
    environment = "production"
  }
}

output "aks_cluster_id" {
  value = azurerm_kubernetes_cluster.aks.id
}
